album_list = [
    {"albumName": "Ready to Die", "artist": "The Notorious B.I.G"},
    {"albumName": "My Beautiful Dark Twisted Fantasy", "artist": "Kanye West"},
    {"albumName": "Nevermind", "artist": "Nirvana"},
    {"albumName": "Take Care", "artist": "Drake"},
    {"albumName": "To Pimp a Butterfly", "artist": "Kendrick Lamar"},
    {"albumName": "Thriller", "artist": "Michael Jackson"},
    {"albumName": "The Blueprint", "artist": "Jay-Z"},
    {"albumName": "The Dark Side of the Moon", "artist": "Pink Floyd"},
    {"albumName": "OK Computer", "artist": "Radiohead"},
    {"albumName": "Aquemini", "artist": "Outkast"},
    {"albumName": "Appetite for Destruction", "artist": "Guns N' Roses"},
    {"albumName": "Enter the Wu-Tang (36 Chambers)", "artist": "Wu-Tang Clan"},
    {"albumName": "Sgt. Pepper's Lonely Hearts Club Band", "artist": "The Beatles"},
    {"albumName": "Lemonade", "artist": "Beyoncé"},
    {"albumName": "Purple Rain", "artist": "Prince"},
    {"albumName": "IV", "artist": "Led Zeppelin"},
    {"albumName": "Life After Death", "artist": "The Notorious B.I.G"},
    {"albumName": "The Marshall Mathers LP", "artist": "Eminem"},
    {
        "albumName": "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
        "artist": "David Bowie",
    },
    {
        "albumName": "Whatever People Say I Am, That's What I'm Not",
        "artist": "Arctic Monkeys",
    },
    {"albumName": "good kid, m.A.A.d city", "artist": "Kendrick Lamar"},
    {"albumName": "Highway 61 Revisited", "artist": "Bob Dylan"},
    {"albumName": "London Calling", "artist": "The Clash"},
    {"albumName": "2014 Forest Hills Drive", "artist": "J. Cole"},
    {"albumName": "Sign o' the Times", "artist": "Prince"},
    {"albumName": "Illmatic", "artist": "Nas"},
    {"albumName": "Back in Black", "artist": "AC/DC"},
    {"albumName": "The College Dropout", "artist": "Kanye West"},
    {"albumName": "Rumours", "artist": "Fleetwood Mac"},
    {"albumName": "Kid A", "artist": "Radiohead"},
    {"albumName": "The Joshua Tree", "artist": "U2"},
    {"albumName": "Licensed to Ill", "artist": "Beastie Boys"},
    {"albumName": "Like a Virgin", "artist": "Madonna"},
    {"albumName": "The Miseducation of Lauryn Hill", "artist": "Lauryn Hill"},
    {"albumName": "Wish You Were Here", "artist": "Pink Floyd"},
    {"albumName": "Sticky Fingers", "artist": "The Rolling Stones"},
    {"albumName": "American Idiot", "artist": "Green Day"},
    {"albumName": "All Eyez on Me", "artist": "2Pac"},
    {
        "albumName": "The Velvet Underground & Nico",
        "artist": "The Velvet Underground & Nico",
    },
    {"albumName": "Blood Sugar Sex Magik", "artist": "Red Hot Chili Peppers"},
    {"albumName": "Yeezus", "artist": "Kanye West"},
    {"albumName": "(What's the Story) Morning Glory?", "artist": "Oasis"},
    {"albumName": "Paul's Boutique", "artist": "Beastie Boys"},
    {"albumName": "Blonde", "artist": "Frank Ocean"},
    {"albumName": "Is This It", "artist": "The Strokes"},
    {"albumName": "Back to Black", "artist": "Amy Winehouse"},
    {"albumName": "Ten", "artist": "Pearl Jam"},
    {"albumName": "Raising Hell", "artist": "Run-D.M.C."},
    {"albumName": "Disintegration", "artist": "The Cure"},
    {"albumName": "A Night at the Opera", "artist": "Queen"},
    {"albumName": "The Chronic", "artist": "Dr. Dre"},
    {"albumName": "Elephant", "artist": "The White Stripes"},
    {"albumName": "Are You Experienced", "artist": "The Jimi Hendrix Experience"},
    {"albumName": "CrazySexyCool", "artist": "TLC"},
    {"albumName": "A Rush of Blood to the Head", "artist": "Coldplay"},
    {"albumName": "DAMN.", "artist": "Kendrick Lamar"},
    {"albumName": "Born to Run", "artist": "Bruce Springsteen"},
    {"albumName": "In Utero", "artist": "Nirvana"},
    {"albumName": "Pet Sounds", "artist": "The Beach Boys"},
    {"albumName": "House of Balloons", "artist": "The Weeknd"},
    {"albumName": "Master of Puppets", "artist": "Metallica"},
    {"albumName": "Rhythm Nation 1814", "artist": "Janet Jackson"},
    {"albumName": "Remain in Light", "artist": "Talking Heads"},
    {"albumName": "In Rainbows", "artist": "Radiohead"},
    {"albumName": "1999", "artist": "Prince"},
    {
        "albumName": "Mellon Collie and the Infinite Sadness",
        "artist": "The Smashing Pumpkins",
    },
    {"albumName": "Melodrama", "artist": "Lorde"},
    {"albumName": "Rage Against the Machine",
        "artist": "Rage Against the Machine"},
    {"albumName": "Section.80", "artist": "Kendrick Lamar"},
    {"albumName": "MTV Unplugged in New York", "artist": "Nirvana"},
    {"albumName": "Bad", "artist": "Michael Jackson"},
    {"albumName": "Legend", "artist": "Bob Marley and The Wailers"},
    {"albumName": "Animals", "artist": "Pink Floyd"},
    {"albumName": "AM", "artist": "Arctic Monkeys"},
    {"albumName": "Tusk", "artist": "Fleetwood Mac"},
    {"albumName": "Definitely Maybe", "artist": "Oasis"},
    {"albumName": "Parachutes", "artist": "Coldplay"},
    {"albumName": "Weezer (The Blue Album)", "artist": "Weezer"},
    {"albumName": "Untitled Unmastered", "artist": "Kendrick Lamar"},
    {"albumName": "Paranoid", "artist": "Black Sabbath"},
    {"albumName": "Badlands", "artist": "Halsey"},
    {"albumName": "The Slim Shady LP", "artist": "Eminem"},
    {"albumName": "Let It Bleed", "artist": "The Rolling Stones"},
    {"albumName": "It Was Written", "artist": "Nas"},
    {"albumName": "Absolution", "artist": "Muse"},
    {"albumName": "2001", "artist": "Dr. Dre"},
    {"albumName": "Abbey Road", "artist": "The Beatles"},
    {"albumName": "Dookie", "artist": "Green Day"},
    {"albumName": "Around the World in a Day", "artist": "Prince"},
    {"albumName": "Demon Days", "artist": "Gorillaz"},
    {"albumName": "Achtung Baby", "artist": "U2"},
    {"albumName": "Late Registration", "artist": "Kanye West"},
    {"albumName": "Born Again", "artist": "The Notorious B.I.G"},
    {"albumName": "Hot Fuss", "artist": "The Killers"},
    {"albumName": "Check Your Head", "artist": "Beastie Boys"},
    {"albumName": "Slippery When Wet", "artist": "Bon Jovi"},
    {"albumName": "Funeral", "artist": "Arcade Fire"},
    {"albumName": "Continuum", "artist": "John Mayer"},
    {"albumName": "The Black Album", "artist": "Jay-Z"},
    {"albumName": "Toys in the Attic", "artist": "Aerosmith"},
    {"albumName": "Blonde", "artist": "Frank Ocean"},
    {"albumName": "Mr. Morale & the Big Steppers", "artist": "Kendrick Lamar"},
    {"albumName": "The Life of Pablo", "artist": "Kanye West"},
    {"albumName": "Rodeo", "artist": "Travis Scott"},
]
