album_list = [
    {"albumName": "The Marshall Mathers LP", "artist": "Eminem"},
    {"albumName": "Thriller", "artist": "Michael Jackson"},
    {"albumName": "Nevermind", "artist": "Nirvana"},
    {"albumName": "The Chronic", "artist": "Dr. Dre"},
    {"albumName": "The Blueprint", "artist": "Jay-Z"},
    {"albumName": "Born to Run", "artist": "Bruce Springsteen"},
    {"albumName": "OK Computer", "artist": "Radiohead"},
    {"albumName": "Back in Black", "artist": "AC/DC"},
    {"albumName": "The Joshua Tree", "artist": "U2"},
    {"albumName": "To Pimp a Butterfly", "artist": "Kendrick Lamar"},
    {"albumName": "Good Kid, M.A.A.D City", "artist": "Kendrick Lamar"},
    {"albumName": "DAMN.", "artist": "Kendrick Lamar"},
    {"albumName": "The Black Album", "artist": "Jay-Z"},
    {"albumName": "Demon Days", "artist": "Gorillaz"},
    {"albumName": "Abbey Road", "artist": "The Beatles"},
    {"albumName": "Licensed to Ill", "artist": "Beastie Boys"},
    {"albumName": "Back to Black", "artist": "Amy Winehouse"},
    {"albumName": "American Idiot", "artist": "Green Day"},
    {"albumName": "The Wall", "artist": "Pink Floyd"},
    {"albumName": "Hot Fuss", "artist": "The Killers"},
    {"albumName": "The Velvet Underground & Nico",
        "artist": "The Velvet Underground"},
    {"albumName": "Illmatic", "artist": "Nas"},
    {"albumName": "Born in the U.S.A.", "artist": "Bruce Springsteen"},
    {"albumName": "A Night at the Opera", "artist": "Queen"},
    {"albumName": "The Miseducation of Lauryn Hill", "artist": "Lauryn Hill"},
    {"albumName": "Hotel California", "artist": "Eagles"},
    {"albumName": "In Utero", "artist": "Nirvana"},
    {"albumName": "The Slim Shady LP", "artist": "Eminem"},
    {"albumName": "The Fame", "artist": "Lady Gaga"},
    {"albumName": "Off the Wall", "artist": "Michael Jackson"},
    {"albumName": "Ten", "artist": "Pearl Jam"},
    {"albumName": "Purple", "artist": "Stone Temple Pilots"},
    {"albumName": "21", "artist": "Adele"},
    {"albumName": "The Blueprint 3", "artist": "Jay-Z"},
    {"albumName": "Sgt. Pepper's Lonely Hearts Club Band", "artist": "The Beatles"},
    {"albumName": "The Eminem Show", "artist": "Eminem"},
    {"albumName": "Channel Orange", "artist": "Frank Ocean"},
    {"albumName": "The Chronic 2001", "artist": "Dr. Dre"},
    {"albumName": "American Beauty", "artist": "Grateful Dead"},
    {"albumName": "Bridge Over Troubled Water", "artist": "Simon & Garfunkel"},
    {"albumName": "Born to Die", "artist": "Lana Del Rey"},
    {"albumName": "Wasting Light", "artist": "Foo Fighters"},
    {"albumName": "Exile on Main St.", "artist": "The Rolling Stones"},
    {"albumName": "The Dark Side of the Moon", "artist": "Pink Floyd"},
    {"albumName": "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
        "artist": "David Bowie"},
    {"albumName": "Brothers", "artist": "The Black Keys"},
    {"albumName": "Californication", "artist": "Red Hot Chili Peppers"},
    {"albumName": "Elephant", "artist": "The White Stripes"},
    {"albumName": "My Beautiful Dark Twisted Fantasy", "artist": "Kanye West"},
    {"albumName": "Sign o' the Times", "artist": "Prince"},
    {"albumName": "Bad", "artist": "Michael Jackson"},
    {"albumName": "Blonde", "artist": "Frank Ocean"},
    {"albumName": "Yeezus", "artist": "Kanye West"},
    {"albumName": "Dookie", "artist": "Green Day"},
    {"albumName": "Are You Experienced", "artist": "Jimi Hendrix"},
    {"albumName": "Rumours", "artist": "Fleetwood Mac"},
    {"albumName": "Boston", "artist": "Boston"},
    {"albumName": "Songs in the Key of Life", "artist": "Stevie Wonder"},
    {"albumName": "Appetite for Destruction", "artist": "Guns N' Roses"},
    {"albumName": "The Doors", "artist": "The Doors"},
    {"albumName": "The College Dropout", "artist": "Kanye West"},
    {"albumName": "Legend", "artist": "Bob Marley & The Wailers"},
    {"albumName": "The Suburbs", "artist": "Arcade Fire"},
    {"albumName": "Speakerboxxx/The Love Below", "artist": "OutKast"},
    {"albumName": "Revolver", "artist": "The Beatles"},
    {"albumName": "Led Zeppelin IV", "artist": "Led Zeppelin"},
    {"albumName": "Purple Rain", "artist": "Prince"},
    {"albumName": "Night Visions", "artist": "Imagine Dragons"},
    {"albumName": "Goodbye Yellow Brick Road", "artist": "Elton John"},
    {"albumName": "Get Rich or Die Tryin'", "artist": "50 Cent"},
    {"albumName": "White Blood Cells", "artist": "The White Stripes"},
    {"albumName": "Traveller", "artist": "Chris Stapleton"},
    {"albumName": "Blonde on Blonde", "artist": "Bob Dylan"},
    {"albumName": "Supernatural", "artist": "Santana"},
    {"albumName": "Rubber Soul", "artist": "The Beatles"},
    {"albumName": "Pet Sounds", "artist": "The Beach Boys"},
    {"albumName": "Straight Outta Compton", "artist": "N.W.A"},
    {"albumName": "...Baby One More Time", "artist": "Britney Spears"},
    {"albumName": "Metallica", "artist": "Metallica"},
    {"albumName": "London Calling", "artist": "The Clash"},
    {"albumName": "Daydream", "artist": "Mariah Carey"},
    {"albumName": "Beyoncé", "artist": "Beyoncé"},
    {"albumName": "Graceland", "artist": "Paul Simon"},
]
