album_list = [
    "Ready to Die By The Notorious B.I.G",
    "My Beautiful Dark Twisted Fantasy By Kanye West",
    "Nevermind By Nirvana",
    "Take Care By Drake",
    "To Pimp a Butterfly By Kendrick Lamar",
    "Thriller By Michael Jackson",
    "The Blueprint By Jay-Z",
    "The Dark Side of the Moon By Pink Floyd",
    "OK Computer By Radiohead",
    "Aquemini By Outkast",
    "Appetite for Destruction By Guns N' Roses",
    "Enter the Wu-Tang (36 Chambers) By Wu-Tang Clan",
    "Sgt. Pepper's Lonely Hearts Club Band By The Beatles",
    "Lemonade By Beyoncé",
    "Purple Rain By Prince",
    "IV By Led Zeppelin",
    "Life After Death By The Notorious B.I.G",
    "The Marshall Mathers LP By Eminem",
    "The Rise and Fall of Ziggy Stardust and the Spiders from Mars By David Bowie",
    "Whatever People Say I Am, That's What I'm Not By Arctic Monkeys",
    "good kid, m.A.A.d city By Kendrick Lamar",
    "Highway 61 Revisited By Bob Dylan",
    "London Calling By The Clash",
    "2014 Forest Hills Drive By J. Cole",
    "Sign o' the Times By Prince",
    "Illmatic By Nas",
    "Back in Black By AC/DC",
    "The College Dropout By Kanye West",
    "Rumours By Fleetwood Mac",
    "Kid A By Radiohead",
    "The Joshua Tree By U2",
    "Licensed to Ill By Beastie Boys",
    "Like a Virgin By Madonna",
    "The Miseducation of Lauryn Hill By Lauryn Hill",
    "Wish You Were Here By Pink Floyd",
    "Sticky Fingers By The Rolling Stones",
    "American Idiot By Green Day",
    "All Eyez on Me By 2Pac",
    "The Velvet Underground & Nico By The Velvet Underground & Nico",
    "Blood Sugar Sex Magik By Red Hot Chili Peppers",
    "Yeezus By Kanye West",
    "(What's the Story) Morning Glory? By Oasis",
    "Paul's Boutique By Beastie Boys",
    "Blonde By Frank Ocean",
    "Is This It By The Strokes",
    "Back to Black By Amy Winehouse",
    "Ten By Pearl Jam",
    "Raising Hell By Run-D.M.C.",
    "Disintegration By The Cure",
    "A Night at the Opera By Queen",
    "The Chronic By Dr. Dre",
    "Elephant By The White Stripes",
    "Are You Experienced By The Jimi Hendrix Experience",
    "CrazySexyCool By TLC",
    "A Rush of Blood to the Head By Coldplay",
    "DAMN. By Kendrick Lamar",
    "Born to Run By Bruce Springsteen",
    "In Utero By Nirvana",
    "Pet Sounds By The Beach Boys",
    "House of Balloons By The Weeknd",
    "Master of Puppets By Metallica",
    "Rhythm Nation 1814 By Janet Jackson",
    "Remain in Light By Talking Heads",
    "In Rainbows By Radiohead",
    "1999 By Prince",
    "Mellon Collie and the Infinite Sadness By The Smashing Pumpkins",
    "Melodrama By Lorde",
    "Rage Against the Machine By Rage Against the Machine",
    "Section.80 By Kendrick Lamar",
    "MTV Unplugged in New York By Nirvana",
    "Bad By Michael Jackson",
    "Legend By Bob Marley and The Wailers",
    "Animals By Pink Floyd",
    "AM By Arctic Monkeys",
    "Tusk By Fleetwood Mac",
    "Definitely Maybe By Oasis",
    "Parachutes By Coldplay",
    "Weezer (The Blue Album) By Weezer",
    "Untitled Unmastered By Kendrick Lamar",
    "Paranoid By Black Sabbath",
    "Badlands By Halsey",
    "The Slim Shady LP By Eminem",
    "Let It Bleed By The Rolling Stones",
    "It Was Written By Nas",
    "Absolution By Muse",
    "2001 By Dr. Dre",
    "Abbey Road By The Beatles",
    "Dookie By Green Day",
    "Around the World in a Day By Prince",
    "Demon Days By Gorillaz",
    "Achtung Baby By U2",
    "Late Registration By Kanye West",
    "Born Again By The Notorious B.I.G",
    "Hot Fuss By The Killers",
    "Check Your Head By Beastie Boys",
    "Slippery When Wet By Bon Jovi",
    "Funeral By Arcade Fire",
    "Continuum By John Mayer",
    "The Black Album By Jay-Z",
    "Toys in the Attic By Aerosmith",
    "Blonde By Frank Ocean",
    "Mr. Morale & the Big Steppers By Kendrick Lamar",
    "The Life of Pablo By Kanye West",
    "Rodeo By Travis Scott"
]